# This tells the CMS what service to use for the backend. In our case, it's GitHub.
backend:
  name: github
  repo: theqourt/shop # Your GitHub username and repo name
  branch: main # Or 'master' if your main branch is called that
  app_id: Ov23liCvfTiF3o90pz8B # This is the Client ID from the GitHub OAuth App you created

# This tells the CMS where to save the images you upload.
media_folder: "assets/images" # The local folder for images in your repository
public_folder: "/assets/images" # The public URL path for those images

# This is a collection, which defines a type of content to manage (like "Products").
collections:
  - name: "products"
    label: "Products"
    # This is the folder where the CMS will store your product data (as separate files).
    folder: "_products"
    # This allows you to create new product entries from the admin panel.
    create: true
    # These are the individual fields for each product entry.
    fields:
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Product Image", name: "image", widget: "image"}
