backend:
  name: github
  repo: theqourt/shop
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    fields:
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Product Image", name: "image", widget: "image"}
