backend:
  name: github
  repo: theqourt/shop
  branch: main
  app_id: Ov23liCvfTiF3o90pz8B # Your Client ID
  # This section tells the CMS to use a different login method.
  auth_type: pkce
  auth_endpoint: https://github.com/login/oauth/authorize
  base_url: https://github.com
  site_url: https://theqourt.github.io/shop/

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    fields:
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Product Image", name: "image", widget: "image"}
